# Generated by Django 4.2.3 on 2023-07-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passengerdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengername', models.CharField(max_length=50)),
                ('Destination', models.CharField(max_length=50)),
            ],
        ),
    ]
