# Generated by Django 4.2.3 on 2023-07-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdetail',
            name='Trainnumber',
            field=models.IntegerField(null=True),
        ),
    ]
