# Generated by Django 4.2.3 on 2023-07-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_passengerdetail_trainnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdetail',
            name='Phonenumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passengerdetail',
            name='Tickets',
            field=models.IntegerField(null=True),
        ),
    ]
